security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        urbanrivals:
            id: App\Security\UserProvider
#    encoders:
#        App\Security\User: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login$
            security: false
        main:
            anonymous: false
            guard:
                authenticators:
                    - App\Security\OauthAuthenticator
            logout:
                path:   /logout
                target: /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
